baseURL = 'https://michaelwang123.github.io/'
languageCode = 'zh-cn'
title = 'Michael的博客'
theme = 'PaperMod'

[params]
  contentPadding = "3rem"
  mainSections = ['posts']  # 指向实际文章目录
  contentMaxWidth = "80ch"
  contentPaddingStyle = "comfortable"

[module]
  [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"
    disable = false  # 确保主题启用

disableKinds = ['taxonomy', 'term', 'rss']  # 仅禁用无关功能
