baseURL = 'https://michaelwang123.github.io/'
languageCode = 'zh-cn'
title = 'Michael的博客'
theme = 'PaperMod'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    lineNos = true
    style = "github"
    lineNumbersInTable = false
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

[params]
  contentPadding = "3rem"
  mainSections = []  # 指向实际文章目录
  contentMaxWidth = "80ch"
  contentPaddingStyle = "comfortable"

[module]
  [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"
    disable = false

disableKinds = ['taxonomy', 'term', 'rss']  # 仅禁用无关功能
